### ISSUE TITLE
Audits: Gas & Limits

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1041]
- Gas Accounting
    - Make sure we've included everything we need to (e.g., dynamic instructions, etc.).
- Memory Expansion Logic
- Syscall Limits
    - No unbounded reads/writes.
- IPLD, etc. Basically, no unbounded datastructures.

@aakoshh, @Jacarte, and others are working on the implementations, this issue is about auditing all of that.

**Comment by Stebalien** [comment]
Interest group includes: @Kubuxu.

**Comment by BlocksOnAChain** [comment]
@jennijuju can we make some availability for Magik to review and audit this? 
I know that @Stebalien  really wants him for this area, when possible. 

Ideally, we can start looking into this in late November - the week of the 28th. 
By saying that, we are flexible on the start date since I know people are really busy, but I think this should be done as part of being a core dev since we are introducing massive changes with FEVM, as we all know.

let me know what you think so that we can plan ahead.

CC: @raulk for visibility

**Comment by jennijuju** [comment]
@BlocksOnAChain we are wondering do we have an ideal start-end date for this effort yet?

**Comment by BlocksOnAChain** [comment]
@Stebalien I think we are ready for @magik6k to start looking at this from today, but we will also discuss it on our internal audits call on Wednesday - if we have some specific remarks

**Comment by Stebalien** [comment]
This has all been taken care of.

**Comment by Stebalien** [comment]
(I.e., I've already gone through and done this as part of finalizing gas numbers)
