### ISSUE TITLE
Audits: FVM Events

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1045]
See https://github.com/filecoin-project/FIPs/pull/483.

Specifically, we need to audit the FVM side of this:

1. Writing events (the syscall).
2. Recording events in the receipt (i.e., forming the event "tree") and maybe persisting it.

Importantly, we need to make sure:

- Users pay for what they use (no spam).
- Snapshots can't balloon (e.g. maybe don't include logs in snapshots?).
- There are no strange unreachable state issues.

**Comment by BlocksOnAChain** [comment]
@Stebalien who do we think would be the best candidate for this audit area?

**Comment by raulk** [comment]
From @jennijuju on Slack:

>> Snapshots can’t balloon (e.g. maybe don’t include logs in snapshots?).
>  (or can you help pointing me to the right person) is it okay for me to assume the following:
>  * we expect application developers to use node service providers?
>  * they will run their own nodes with their desired log filters, however, they will only care about the epoch(contract deployment +1, forward) information, thus syncing from a snapshot without historical logs, then after sycned from the snapshot, enable the log filters to start getting logs is acceptable
> * block explorers likely will not sync from snapshot, and we shall expect them to enable log events savings upon upgrade
> if assumptions are true above, i believe we dont have to include logs in snapshot
> otherwise, we will have to do some 🤔  & typing
> @travisperson --  only for you awareness for now

**Comment by jennijuju** [comment]
good call out on snapshots (thank you for always thinking of everything @Stebalien , you are really gooooooood at what you do you know that right?)

>  (e.g. maybe don't include logs in snapshots?).
on this i'd like to know if the following assumption is correct:
- do we expect application developers to use node service providers? how many node service provider will exist upon on mainnet launch?
- application develop may also run their own nodes with their desired log filters, however, they will only care about the epoch(contract deployment +1, forward) information, thus syncing from a snapshot without historical logs, then after sycned from the snapshot, enable the log filters to start getting logs is acceptable
- block explorers likely will not sync from snapshot, and we shall expect them to enable log events savings upon upgrade
if the assumptions are true above, i believe we don't have to include logs in snapshot
otherwise, we will have to do some :thinking_face: &: :cattyping:
cc @travisperson for awareness

**Comment by raulk** [comment]
> * do we expect application developers to use node service providers? how many node service provider will exist upon on mainnet launch?

Yes, and no. Yes because most devs will likely use hosted providers (e.g. Glif -- cc @eshon for listing others). No because this shouldn't be the only mode in which they get to consume logs.

> application develop may also run their own nodes with their desired log filters

Yep.

> they will only care about the epoch(contract deployment +1, forward) information

Maybe yes, maybe no. We shouldn't assume this as dapp logic can be very varied, and we should plan for a world of radical composibility between contracts. Thus, dapp operator A may be interested in the events emitted by contract B, which may have been deployed earlier than A.

---

Generally speaking I think we should plan for emitting log-specific snapshots, **separate** from the main chain and state snapshots, which we retain for R days performing continuous rotation. These are purely for _convenience_ (hence the time bounding), as you can always calculate logs and receipts from state tree and messages (already in chain snapshots).

For example:

```
## chain snapshot containing the full chain + state trees for N epochs
## retained forever
1419120_2022_10_24T18_00_00Z.car.zst
## companion events snapshot for N epochs
## deleted after R days
1419120_2022_10_24T18_00_00Z.events.car.zst
```

**Comment by BlocksOnAChain** [comment]
@Kubuxu reported that this audit is done, and his preliminary findings doc is shared here(private): https://www.notion.so/pl-strflt/Actor-Events-Review-9824ea0aa5964a4ca0818cb0bd5951d9
