### ISSUE TITLE
Charge for table growing

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1075]
We don't curently charge for table growing, but we should. According to the wasmtime docs, each table element requires one usize of memory (host memory).

Proposal: Charge 8 bytes per table element.

1. Instrument and charge for zeroing in wasm.
2. Account for the expanded table memory in wasm.

**Comment by aakoshh** [comment]
Just looking at where this could be implemented.

When an instance is allocated by the pooling allocator, it already [gets the maximum number of table elements](https://github.com/bytecodealliance/wasmtime/blob/v2.0.1/crates/runtime/src/instance/allocator/pooling.rs#L484-L488) writeable to it. The table will be static; it will [start from the minimum](https://github.com/bytecodealliance/wasmtime/blob/v2.0.1/crates/runtime/src/table.rs#L196) and account for growth, but this for a static table [is just a formality](https://github.com/bytecodealliance/wasmtime/blob/v2.0.1/crates/runtime/src/table.rs#L360-L364) of checking the limits. 

I'm not sure at the moment how to figure out the minimum table size for the module. Wasmtime doesn't expose the memory plans, and I resorted to calling `inst.get_memory("memory")`, which was an established well known name. I don't see us using `inst.get_table` at the moment. The instance limits only allow 1 table per module by default, so I'm assuming this is the function table (because all elements in it have to have the same type). Does that have some well-known name?

Something I don't understand is that in wasmtime we can see [table grow code being translated](https://github.com/bytecodealliance/wasmtime/blob/v2.0.1/cranelift/wasm/src/code_translator.rs#L1352-L1364), but when I follow [how we instrument memory growth](https://github.com/filecoin-project/fvm-wasm-instrument/blob/master/src/gas_metering/mod.rs#L468), there is [no such thing](https://github.com/paritytech/parity-wasm/blob/master/src/elements/ops.rs#L650) as a grow table instruction. At the moment I'm not sure where to inject any charge for growing the table. Also not sure where it would grow if it's only for functions - can more of them be added during runtime?

**Comment by Stebalien** [comment]
Status: We now charge for table init, but not for growing.

We now need to charge for _growing_, but should do this when instrumenting instructions.
