### ISSUE TITLE
MMVP Account Abstraction

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1204]
Basically, the goal is to implement logic that behaves like account abstraction would, but only for Ethereum accounts. Any solution must be transparently upgradable into _full_ account abstraction. The _implementation_ can change, but the interfaces should be network compatible and we shouldn't need to maintain any long-term hacks after implementing full account abstraction.

# Design

## Signatures

1. [x] Introduce a new "delegated" signature type in Filecoin clients. We'll need this anyways.
2. [ ] Create a new Ethereum EOA actor.
3. [ ] Instead of checking if the "from" address belongs to an FIL account, allow messages from Ethereum EOA accounts with f410 addresses and embryos with f410 addresses _if_ the signature type is "delegated".
4. [x] Verify these "delegated" signatures as we would in full account abstraction (by reconstructing the original Ethereum transaction), but do it in lotus instead of calling into the FVM.

## Automatic Instantiation

1. [ ] Inside the FVM, on message execution, if a message sender is an embryo with an f410 address, automatically deploy an Ethereum EOA at that (the sender's) address, then send the message.

**Comment by anorth** [comment]
How do you reconcile verifying delegated signatures in Lotus (without the VM) and automatic instantiation on send from an embryo. How does lotus know how to validate the signature? Is it implicit in the f410 address? How can we move that logic into the VM in the future for other AA actors so that they too can validate a signature prior to deploying a actor (even if that actor is limited to a single code CID per address manager and, presumably, no constructor arguments).

Can you tell me a story about how this will be implemented in M2.2, even if we don't do any of the work for that yet?

Automatic instantiation wasn't covered in https://github.com/filecoin-project/FIPs/discussions/490. I know we discussed it further but don't know where the discussion results are recorded. It remains the piece that I am most hesitant about.

**Comment by jennijuju** [comment]
@arajasek can close?
