### ISSUE TITLE
EVM: Consider rejecting calls to 0xff00.............ID addresses when the target has a real EVM address

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1276]
We already have to lookup the type of the actor we're calling, so it should be pretty easy to not allow ID-in-Ethereum addresses when calling EVM contracts (and accounts). This would avoid an awkward situation where all EVM actors actually have _two_ EVM addresses.

**Comment by maciejwitowski** [comment]
@Stebalien @mriise Did you decide if we want to do this in the end? What milestone and priority?

**Comment by mriise** [comment]
I think we do, it prevents a weird edge case from getting too weird. Adding milestone and priority. The only concern I can see for doing this is potential breakages in the Filecoin.sol libs and other things that interact closer to the system that might've relied on always resolving the ID address and calling that. 

Though... now that i think about it, it's not as simple as relying on the builtin "type" since there can be multiple actor types that have EVM address... in order to properly say we reject this for all EVM addresses we will need to do an actual lookup for an actor's delegate address. Otherwise we will be getting in the situation we ran into the other week where we have multiple different implementations of "is this an EVM thing". e.g. https://github.com/filecoin-project/builtin-actors/pull/986

**Comment by Stebalien** [comment]
So, the motivation is to avoid "double counting". E.g., when voting/staking. But the answer is non-obvious so I'd punt this for a week until we can nail something down.

- We probably need to check inside the `BALANCE` opcode (and friends).
- We may even need to add some checks inside lotus.
- This relates to #1254.

**Comment by raulk** [comment]
> So, the motivation is to avoid "double counting". E.g., when voting/staking.

Hm, in this case the vote/stake would be stored in state, right? How would we canonicalize the address in that case?
I don't think we can cover all cases reliably since most of them reside in user land. I would imagine this is an announced user caveat rather than something we can resolve universally (on the level of the gas limit caveat on CALL).

**Comment by Stebalien** [comment]
> Also note that in many cases, contracts will use CALLER or ORIGIN (unless some delegation, nomination, appointment, or something is happening where an address is conveyed in input data), all of which return ID addresses.

If and only if the caller doesn't have a proper Ethereum address.

---

I've been talking about this with @wadeAlexC and we'll have issues any which way we go, so we might as well leave this as-is. Basically:

1. We want to support calling into native actors with `CALL` so that (future) native actors can implement EVM standards (e.g., ERC20).
2. It would be confusing to support this ID address convention for some actors and not others.

I'm going to close this for now as I don't think there's anything to do here.
