### ISSUE TITLE
Confusing error message when sending calls to not deployed contracts

### ISSUE THREAD

**Issue by shrenujbansal** [filecoin-project/ref-fvm#1304]
When sending a message using EthCall to an address that doesn't yet exist, we get the below error message:

ERROR: message execution failed: exit 22, reason: message failed with backtrace:
00: f01004 (method 2) -- embryo actors may only receive messages on method 0 (22)

This isn't really descriptive of the actual issue which is a simple user error and can send the user searching down the wrong rabbit hole.

**Comment by Stebalien** [comment]
Basically, the issue is that we auto-create embryos on first send, but then the send fails immediately because it's not method 0. This is consistent with accounts, but confusing.

We can:

1. Reject the send _first_ if the method isn't 0 (could do the same thing for accounts?).
2. Improve the error message (e.g., detect this case inside the FVM, and alter the backtrace to make the situation clear.

**Comment by raulk** [comment]
We should fix this before the launch of Hyperspace. It's a usability kink that others are likely to encounter.

**Comment by Stebalien** [comment]
Proposal:

1. Have some form of backtrace error annotation/replacement hook in the machine.
2. Register this hook with the backtrace itself.
3. When pushing a frame onto the backtrace (inside the backtrace logic itself), maybe replace an error with a better error message (or annotate the error message) with this hook.
