### ISSUE TITLE
Audit: Confirm correct opcode/tx behaviour with precompiles

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#1377]
* Check what Ethereum does when contracts call opcodes like BALANCE, EXTCODE*, etc. on precompile addresses.
* I suspect these addresses receive the same treatment as accounts or the zero address.
* Also check what happens if an EEOA submits a bare transfer transaction to a precompile address. I assume same treatment as zero address in Ethereum. What do we do?
* Ensure that we don't do anything weird.

**Comment by Stebalien** [comment]
> Check what Ethereum does when contracts call opcodes like BALANCE, EXTCODE*, etc. on precompile addresses.

The EVM returns:

1. 0 balance (which we already do).
2. Empty code/length (which we also do).
3. The hash of empty code (done).

> Also check what happens if an EEOA submits a bare transfer transaction to a precompile address. I assume same treatment as zero address in Ethereum. What do we do?

Lol. Yes, I think it just sends the funds... In our case, it'll create an embryo at that address. It shouldn't have any side-effects (nothing can be deployed there) but it's still interesting.

**Comment by maciejwitowski** [comment]
no negative side-effects + being conservative with the scope atm => add it to post-launch backlog?

**Comment by wadeAlexC** [comment]
@Stebalien Just wanted to point out that your last 2 points are a little incomplete:

> 2. In FEVM, calling a precompile from off-chain will transfer the funds to an embryo with the precompile's address while transfering funds on-chain won't do anything (except call_actor).
> 3. In FEVM, getting the balance of a precompile will always return 0, even if the associated "account" (embryo) has a non-zero balance.

First, transferring funds on-chain also works if you use `selfdestruct` to move the funds.

Second, getting the balance of the precompile will return 0 if you pass the standard precompile-like EthAddress to the balance opcode. However, if you pass the ID address of the precompile Embryo, it returns a normal balance.

Not sure these are important edge cases, but thought I'd mention them since I just ran into them during testing.

**Comment by wadeAlexC** [comment]
Followup, you can also ask about the balance of the precompile using its EthAddress if you selfdestructed it some funds.

So for precompiles, the BALANCE opcode only tracks the funds sent to it via off-chain message or selfdestruct.

And the opcode does function for both the Embryo's EthAddress and ID address.

**Comment by wadeAlexC** [comment]
Thinking about this some more, another edge case is that once you have an ID address for a precompile, you can probably pass that ID address into CALL/STATICCALL/DELEGATECALL, etc and get the typical "embryo" experience - i.e. it's like calling an EOA or other embryo.

So what we can expect for mainnet as it stands now, is that each of the precompiles will have an ID address (because people will send Fil to them for whatever reason), but those ID addresses behave differently than their EthAddress counterparts.

**Comment by wadeAlexC** [comment]
... and I guess that means that you'll be able to transfer them value via CALL, as long as you use their ID addresses.

**Comment by Stebalien** [comment]
The situation has changed a bit since I wrote that comment:

1. Selfdestruct now allows a precompile address.
2. Getting the balance of a precompile address will "just work".
3. Transferring funds to a precompile will also "just work".

This is due to two changes:

1. `From<EthAddress> for Address` no longer special-cases precompile addresses.
2. We now explicitly transfer funds when calling a precompile (https://github.com/filecoin-project/builtin-actors/blob/68f3f79fcb7ccf6a990fbc0218e1d33e8a8a347d/actors/evm/src/interpreter/precompiles/mod.rs#L97-L99)

**Comment by Stebalien** [comment]
> Thinking about this some more, another edge case is that once you have an ID address for a precompile, you can probably pass that ID address into CALL/STATICCALL/DELEGATECALL, etc and get the typical "embryo" experience - i.e. it's like calling an EOA or other embryo.

Ew. But I think that may have to fall into the category of "don't do that". IMO, treating the ID addresses as precompiles is worse.
