### ISSUE TITLE
tipset_cid syscall and null blocks

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/ref-fvm#1379]
Question raised from audit 

"Potentially an issue: assuming the behavior above for null epochs: if null epochs last a long time (say in an attack or syncing a weird fork) then this syscall could potentially go way over the 900 "

"How does tipset_cid work in case of many many null blocks and does it violate guarantees between node and ref-vm? ".

**Comment by Stebalien** [comment]
We currently ask for the tipset before the null rounds. E.g.:

```
tipset: a _ _ b _ _ _ c <- current height
height: 1 2 3 4 5 6 7 8
```

Asking for, e.g., epochs 1, 2, or 3 will return `a`. Asking for 8 will return `c`. Asking for 5 will return `b`.

The implicit requirement is that users need all the tipsets up to and including the last tipset before finality. However, snapshots include all tipsets since genesis _anyways_ so this shouldn't be an issue.

Really, the only reason we _have_ a limit is to limit the size of the tipset cache.
