### ISSUE TITLE
Charge gas for the tipset_cid syscall

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/ref-fvm#1633]
As far as I can tell, there's no explicit gas charged for this operation, beyond the base syscall cost of 14k. That seems like a problem, because it could involve walking up 900 epochs (restricted to 256 in its only use case right now), and performing an uncharged hash (uncharged because the CID computation happens in the client).

**Comment by arajasek** [comment]
Also, why does the Runtime implementation of this method in builtin-actors return an Option, and not a Result?

**Comment by Stebalien** [comment]
Well, this is definitely broken. It _should_ be charging the extern cost (21k gas).

But yeah, we're also not charging for the walk. I thought we had a cache, but it looks like the cache doesn't actually provide O(1) lookups.

The simple solution would be to:

1. Do some gas modeling with a simple test in lotus.
2. Add 21k to account for crossing the extern boundary.

The _right_ solution would be to test it from the FVM itself.

**Comment by Stebalien** [comment]
> Also, why does the Runtime implementation of this method in builtin-actors return an Option, and not a Result?

Historical reasons, IIRC. The method _now_ takes the epoch at which to look, so it has two failure cases: "lookback limit exceeded" and "epoch beyond current". Previously, it would take the lookback distance so it only had one failure case and an option was convenient (I'm just making this up, I have no idea what the actual reason was).

**Comment by Stebalien** [comment]
Yes.
