### ISSUE TITLE
Trace requests (for Internal Transaction support in Blockscout)

### ISSUE THREAD

**Issue by eshon** [filecoin-project/ref-fvm#1793]
To enable Internal Transactions in the new FEVM block explorer Blockscout, the following trace API is needed:

https://docs.blockscout.com/for-developers/information-and-settings/node-tracing-json-rpc-requirements#enable-tracing-to-fetch-internal-transactions

**Comment by eshon** [comment]
To enable Internal Transactions in the new FEVM block explorer Blockscout, the following trace API is needed:

https://docs.blockscout.com/for-developers/information-and-settings/node-tracing-json-rpc-requirements#enable-tracing-to-fetch-internal-transactions

**Comment by eshon** [comment]
Dune Analytics and ngram also need this for integration.

**Comment by eshon** [comment]
Update from Dune on the requests they need:

Head - eth_blockNumber
Block - eth_getBlockByNumber
Traces - debug_traceTransaction or trace_block (Needed for decoding)
Receipts - eth_getTransactionReceipt (one call per transaction)
Health - net_version

cc: @fridrik01

**Comment by Stebalien** [comment]
Status:

- We landed an implementation of `trace_block`, but need another pass to resolve some TODOs.
- `eth_getBlockByNumber` and `eth_blockNumber` are already implemented. However, the former will still stumble a bit on "native" messages. `trace_block` has some very special logic for handling native transactions, but we haven't ported those over to `eth_getBlockByNumber` yet.
- `ethGetTransactionReceipt` exists.
- `net_version` exists.

At the moment, @fridrik01 is working on other things. We'll get back to this, but we all needed a break as it turned out that mapping Filecoin semantics onto Ethereum was... very painful.

**Comment by Stebalien** [comment]
Also, I thought we _weren't_ doing Dune because they wanted 500k. Did that change again?

**Comment by eshon** [comment]
Ah sorry - @Stebalien Can you plz delete your comment? Price negotiations like that are normally confidential / internal to an organization.
