### ISSUE TITLE
Kernel block operations should fail with InvalidHandle

### ISSUE THREAD

**Issue by anorth** [filecoin-project/ref-fvm#453]
The kernel `block_read` and `block_stat` operations should return `InvalidHandle` on failure, not `IllegalArgument`, in order for syscalls like `send()` to match their [spec](https://github.com/filecoin-project/fvm-specs/blob/main/07-errors.md).

**Comment by anorth** [comment]
Investigating a bit further:
- Operations in kernel/blocks.rs return a BlockError
- There are six different values for BlockError (only two of which appear to be used: InvalidHandle and TooManyBlocks) but they don't self-identify whether they should be fatal (non-reproducible bug) or a persistent reproducible error. I _think_ both the latter.
- BlockError is not automatically convertible to ExecutionError (of type syscall or fatal), and there's a comment in kernel/error.rs noting that conversions are omitted by design, forcing user to chose which type of execution error

Given this, the easy path in the code was to add `.or_illegal_argument()` to calls returning a BlockError but that need an ExecutionError, but this seems wrong. For this case, I think the two values actually used have clear SyscallError counterparts (InvalidHandle and LimitExceeded) and there should be an explicit BlockError->ExecutionError function (`From`?) that maps all the values (deleting the unused ones for now).

`or_illegal_argument()` is used a lot and my guess would be that many of the uses are wrong in a similar way. I reckon we should remove the method as it promotes laziness. But alternatively or simultaneously, we need this reproducible vs non-reproducible distinction made for all errors, as low down as we can.

What say you @raulk @Stebalien @dignifiedquire ?

**Comment by Stebalien** [comment]
For some context: this code is pretty old (by our standards) and was written with M2 in mind (hence all the errors). Once reality hit and we scoped back a bit, most of the error cases lost their meaning (for now).

In general, we've avoided implicit conversions to force the user to chose if the error is "fatal" or not. We provide the convenience method for `or_illegal_argument` simply because _most_ errors are, in fact, an illegal argument. Sometimes it's hard to tell, but we don't really have a better option.

In this case:

1. Yes, delete the cases that don't matter.
2. It _does_ look like there's a safe conversion to syscall errors, so go ahead and implement that. My main concern is choosing between "fatal" and non-fatal, really.
