### ISSUE TITLE
EVM runtime: Implement CREATE, CREATE2 opcodes

### ISSUE THREAD

**Issue by karim-agha** [filecoin-project/ref-fvm#680]

**Comment by shamb0** [comment]
Interested to work on this issue, May I know is it
available ?
 
Looks like existing implementation of `fil_actor_evm`,
is based on one actor container managing bytecode & 
state of single contract.

Does it make-sense, to modify the implementation like,
one actor container to manage multiple contracts ?
 
I hope, in order to support `CREATE & CREATE2`, contract deployment shall be moved out of actor constructor method & handle it via new explicit new actor methods, & actor's state variables need to be adopted to support bytecode & states of multiple contracts without collision.
