### ISSUE TITLE
EVM runtime: Implement DELEGATECALL

### ISSUE THREAD

**Issue by karim-agha** [filecoin-project/ref-fvm#685]
Running an EVM bytecode in the context of another actor's state CID.

**Comment by Stebalien** [comment]
Ok, I was wrong here. `DELEGATECALL` and `CALLCODE` take a _gas_ limit, which means we need to be able to stop execution when we reach some amount of _Filecoin_ gas. That means this code _must_ run in a different invocation container.

IMO, our only real option here is to recursively call into ourselves adding a new `invoke_with_code(evm_bytecode, params, invocation_context, etc...)` method to the EVM actor.

When called, this method would:

1. Validate that the caller is self.
2. Mock the invocation context (specifically, the "ultimate" caller, value, etc).
3. Execute the provided evm bytecode instead of the actor's evm bytecode.

We'll have to _very carefully_ filter all calls from `CALLACTOR` to ensure they don't try to call `invoke_with_code` on ourselves. Really, we might just want to forbid self CALLACTOR calls.

**Comment by raulk** [comment]
Makes sense, but that would mean the caller needs to save its state to the blockstore so that the new invocation container can "see" it. 

Note to self: EVM memory is not shared when DELEGATECALLing.

**Comment by Stebalien** [comment]
> Makes sense, but that would mean the caller needs to save its pre-call state to the blockstore so that the new invocation container can "see" it?

Unfortunately, yes.

**Comment by raulk** [comment]
Did you consider sending the root CID as a param (ie. sending the intermediate sub DAG)? Doing so would save a few syscalls. It might be a bit delicate because we don't have proper reachability analysis yet, but it may not entail any risk at this stage either?

**Comment by Stebalien** [comment]
Ah, you mean the root state CID? You're right, we could do that. We'd need to flush the HAMT (write the blocks from memory into the FVM), but we wouldn't need to call `set_root` (wouldn't need to pay the costs for persisting).

Honestly, I don't think this is something we should spend any time optimizing. As far as I know, most contracts that use DELEGATECALL:

1. Lookup the target address in state.
2. Forward the message to the target address.
3. Return the result.

I.e., they rarely _write_ to their own state.
