### ISSUE TITLE
EVM runtime: Map FVM context info to EVM opcodes

### ISSUE THREAD

**Issue by karim-agha** [filecoin-project/ref-fvm#689]
## See https://github.com/filecoin-project/ref-fvm/issues/689#issuecomment-1208032152 for the updated view and state

---

Implement opcodes that query the transaction context:
- `ORIGIN` 
- `CALLVALUE` 
- `ADDRESS` 
- `BLOCK_NUMBER` 
- `TIMESTAMP` 
- `CALLER` 
- `BLOCKHASH` 
- `CHAINID` 
- `BASEFEE` 
- `DIFFICULTY` 
- `GASLIMIT`

**Comment by raulk** [comment]
Some initial notes:

- `ORIGIN` => requires a new syscall: #300.
- CALLVALUE => maps to the value received in the transaction context.
- ADDRESS => TBD -- we need to track this separately as it depends on the Addressing spec (https://github.com/filecoin-project/ref-fvm/issues/690).
- BLOCK_NUMBER => epoch.
- TIMESTAMP => this is probably tricky because we'll need to know the genesis timestamp to resolve this (as it'll vary per network).
- CALLER => for now, return the ID address of the caller until https://github.com/filecoin-project/ref-fvm/issues/690 is solved.
- BLOCKHASH => this is tricky. I don't think we can return _just_ the hash of the first block in the parent tipset, as we probably lose some security in the face of a reorg that preserves the first block.
- CHAINID => return value zero until #681?
- BASEFEE => return the basefee
- DIFFICULTY => return 0
- GASLIMIT => returns the block's gas limit. We may need a syscall or a context parameter to return this value to avoid hardcoding the 15B gas assumption.

**Comment by raulk** [comment]
Now tracking more granularly in https://github.com/filecoin-project/ref-fvm/issues/864 and https://github.com/filecoin-project/ref-fvm/issues/865.
