### ISSUE TITLE
  error[E0603]: trait `FromStr` is private

### ISSUE THREAD

**Issue by derricktan23** [filecoin-project/ref-fvm#705]
Encountered an bug : error[E0603]: trait `FromStr` is private

Currently, is there a way to convert from String to Filecoin Address or Vice-Versa, eg : impl FromStr ?
https://github.com/filecoin-project/ref-fvm/blob/master/shared/src/address/mod.rs

Logs are as follows
```
    --> /root/rust_programming/meta_file/src/layer_zero/erc721.rs:11:26
     |
  11 | use fvm_shared::address::FromStr;
     |                          ^^^^^^^ private trait
     |
  note: the trait `FromStr` is defined here
```

**Comment by raulk** [comment]
The `FromStr` trait is a standard trait. What's happening here is that you're trying to import the symbol through its presence in the `address` module -- this is not correct usage because that trait is not re-exported. If anything, you need to import `std::str::FromStr`. However, take a look at the tests here for examples of address parsing code: https://github.com/filecoin-project/ref-fvm/blob/77664f633938a67ee44bf558aa6482cd64ac5166/shared/tests/address_test.rs#L564-L593.
