### ISSUE TITLE
Rename the EAM

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#972]
EAM stands for "Ethereum Address Manager". It is, unfortunately _very easily confused_ with EVM.

We should probably call it something else before the name gets too ingrained.

**Comment by raulk** [comment]
I think EAM is fine. Alternatively we could call it ECF (Ethereum Contract Factory), but that tightens its scope to just that, which limits our ability to create accounts and other future developments. EAM is generic enough and I'm happy to live with the one-letter difference because I don't expect it to surface much anyway in user-facing things.
