### ISSUE TITLE
EVM: special-casing the 21000 gas limit on CALL

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#980]
## Context

The FEVM runtime does not perform Ethereum gas accounting. This has two main implications:

1. Opcodes _returning_ gas (e.g. GAS, GASLIMIT) will return Filecoin gas, which may no longer line up with assumptions that contracts may be making (e.g. taking different decision branches based on gas available)
2. Opcodes _taking_ gas (e.g. CALL) will expect Filecoin gas, whereas existing contracts may be passing well-known Ethereum gas values which are meaningless in FEVM.

## Problem

We believe (1) to be very infrequent and negligible in terms of product implications.

On the contrary, we believe that (2) is more prevalent, especifically the combination of CALL with a 21000 gas limit. This is frequently used to prevent callees from executing code (and thus implicitly restricts callees to be accounts or nil-coded contracts). In other words, to guarantee the call can only be a naked transfer. More information on the where 21000 comes from here: https://ethereum.stackexchange.com/questions/34674/where-does-the-number-21000-come-from-for-the-base-gas-consumption-in-ethereum

## Proposed solution

Special-case `CALL` in the FEVM runtime carrying a 21000 gas limit and no message parameters, treating them as a native value transfer to the callee (`send::send` with method number 0).

**Comment by maciejwitowski** [comment]
@raulk sounds like we need this for M2.1

**Comment by vyzo** [comment]
We need it with https://github.com/filecoin-project/builtin-actors/pull/885, it will be very ugly with those hardcoded 21ks failing with fil gas usage orders of magnitude higher than evm.

**Comment by Stebalien** [comment]
So, it's a _little_ more complex:

1. It does invoke code, so the called actor has a chance to reject the transfer.
2. The called actor has a chance to emit an event (e.g., to record the transfer).

Reducing this to a bare send would likely have unfortunate consequences (e.g., transfer logs won't happen).

I'm not entirely sure what we should do here (other than track EVM gas). One potential solution is to add more flags:

1. Remove the value transfer limitation of the read-only flag. I.e., apply the read-only flag _after_ transferring value (enforcing the value transfer limitation in the _caller_).
2. Split the read-only flag into "read-only" and "silent" flags (where it's possible to call an actor in "read-only" mode while still allowing logs.
3. Add an "isolated" flag to prevent sub-calls.
4. Determine and set a minimum gas value that's large enough log a few things, but not _too_ large.

Another potential solution is to do this _entirely_ within the EVM by adding a new "restricted-call" endpoint. Yeah, actually, this is likely the best solution for now.

1. When calling a native contract, demote to METHOD_SEND.
2. When calling an EVM contract, call a RestrictedCall endpoint (with some reasonable gas limit).

**Comment by vyzo** [comment]
Ok, but what's a reasonable gas limit?

**Comment by Stebalien** [comment]
No idea? I think that's something we need to benchmark. I.e., see how much gas it costs to:

1. Transfer some value.
2. Read params.
3. Read some state.
4. Log a couple of things.
5. Return a value.

But we can implement the restrictions _first_, then figure out the correct gas values.

**Comment by vyzo** [comment]
Ok. I also don't think we need a special restricted endpoint if we do get this magic value right; just a normal contract invocation will do.

**Comment by vyzo** [comment]
Also fvm-bench to the rescue!

**Comment by Stebalien** [comment]
We can try... but we're not allowed to "save state" (and our current charges for that are pretty limited). I don't think we're going to be able to come up with a good value here.

**Comment by raulk** [comment]
> It does invoke code, so the called actor has a chance to reject the transfer.

Mind elaborating on this? 21000 is the base gas cost of covering a bare send in Ethereum. If the receiver is a contract (i.e. has non-nil bytecode), that bytecode would run, resulting in 21000 + bytecode execution gas.

I think the bytecode execution gas will always be > 0 except if the contract is comprised of a _sole_ STOP, REVERT, or RETURN  instruction, which are the only instructions that have 0 minimum cost.

(I don't know if Ethereum applies a dispatch cost, though, so there _may_ be an extra cost for running non-nil bytecode which would send the cost over 21000).

---

Reading [this post](https://ethereum-magicians.org/t/some-medium-term-dust-cleanup-ideas/6287#why-do-txs-cost-21000-gas-1) from Vitalik makes me think that 21000 is the cost of an _external_ send (includes signature validation), so this issue might be entirely moot for the CALL opcode, but instead we should apply the special-casing in the JSON-RPC endpoint?

**Comment by Stebalien** [comment]
Proposal:

1. If the specified gas is zero and the value is non-zero (ew), bump add a stipend to the gas (unlike the EVM, we're charging for this stipend).
2. As @vyzo suggests, add a new special entrypoint that we _only_ use when the gas value is zero.

This isn't _quite_ what the EVM does, but it should be "good enough". However, we're going to need to test this _carefully_.

**Comment by wadeAlexC** [comment]
> 2\. The caller (e.g., solidity) doesn't specify 2300, it specifies 0 and the _EVM_ just ever so kindly _grants_ 2300 gas to the called function if the value transfer is > 0. Like, out of thin air.

No - the EVM does charge for the stipend. It's just not explicitly passed in via the CALL instruction.

And Solidity does specify 2300, but only in the case where the `send` or `transfer` method is being used, with zero value.

**Comment by wadeAlexC** [comment]
I also said yesterday that it was possible for these 2300 gas calls to send calldata. While this is technically true, i want to clarify that it would need to be manually implemented. 

`send` and `transfer` are the only Solidity methods that deal with the 2300 gas stipend, and those do NOT send calldata.

`call` is the other method to call contracts, and that forwards all gas by default.

**Comment by Stebalien** [comment]
> No - the EVM does charge for the stipend. It's just not explicitly passed in via the CALL instruction.

You sure? I guess the _other_ charges may cover it, but the stipend is handled _after_ gas is charged.

**Comment by wadeAlexC** [comment]
#### Proposal

Alright -- my proposal is that if the `CALL` opcode is invoked and:
* `<= 2300` gas is provided
* Input data size is 0

... Then we should treat this as a METHOD_SEND instead - regardless of the value being transferred.

#### Benefits

The main goal of this proposal is to support Solidity's `address.send` and `address.transfer` syntax as-is, without changing the security assumptions that go along with using these methods. Ideally, use of `address.call` should also be minimally-effected.

I think this proposal allows us to support Solidity's `addr.send` and `addr.transfer`, which will effectively be zero-code-execution value transfers. I think this is a good compromise, because that's the only context they're used in these days, anyway.

#### Short History

Asking around, the consensus seems to be that "2300 gas" was only chosen because it should be "enough gas to log an event, but not to SSTORE/other state changes." And since events aren't reflected in a smart contract's state, I think the security-critical feature is that value is being transferred, not that we're doing it with "just enough" execution to also log an event.

I actually found a blog post from Ethereum's past which I feel supports this idea - during the Istanbul hard fork, the price of the SLOAD opcode was changed. This apparently broke some Aragon contracts which were relying on `addr.send`-type interactions having enough gas to perform an SLOAD, among other things. Here's an excerpt:

> This new version of the AppProxy contract was specifically designed against the increased cost of SLOAD, and will not change behaviours following the hard fork.
> ...
> Unfortunately, AppProxy contracts are not themselves upgradeable, and hence older organizations are not able to receive this change. Our original AppProxy contracts were designed with the best practices at the time, following the recommended gas stipend. The Istanbul hard fork pushes their costs of receiving ETH via send() or transfer() to 2359 gas, or a mere 59 gas above the available limit.

[reference link - scroll to "technical details"](https://blog.aragon.org/istanbul-hard-fork-impact/)

In our case, Aragon's contracts would not break entirely, as they could still receive ETH (albeit without whatever logic they were running on the receiving contract).

#### Edge Case

A potential edge case of this change was brought to my attention -- 

> I am already wondering about corner-cases in which you would then e.g. give little gas to a contract, cause it to go below 2300 gas when it tries to do a "full-gas-CALL" this way, which would usually fail as the receiving side reverts the transaction, but is now succeeding as you replaced it with an opcode which doesn't revert...

So this refers to an attacker maliciously supplying "just enough" gas to a contract to the point where it tries to execute a normal `address.call`-type interaction, but the contract only has `< 2300 gas` at the point of CALL. According to this proposal, this would become a METHOD_SEND instead, which may succeed where a normal CALL would have failed (due to logical checks in the receiving contract, for example).

I think this represents a very very small edge case - and in the FEVM's case, even smaller still because 2300 gas isn't enough to do much of anything, anyway. Even if this hypothetical call had 2301 gas, I doubt anything meaningful is happening in the receiver. Would appreciate someone that knows more about gas costs per operation to weigh in here.

One possible way to make this edge case even smaller is to only apply the proposal to gas values of `0` and `2300` precisely, and nothing in-between these values. I think that'd be a fine way to approach this, given that the goal is to support `send` and `transfer`, which will only use those two values.

**Comment by wadeAlexC** [comment]
BTW there is one more alternative - to only apply the proposal to CALLs with 0 gas passed in.

This also works because the only case in which Solidity passes in 2300 is for a `address.send(0 wei)`, which is a nonsensical operation that I'm fairly certain no one actually uses.

So that's an option too, and may be even simpler/clearer to devs.

**Comment by Stebalien** [comment]
> Proposal

That's what we currently do.

You're right that this won't affect _on-chain_ state, so we may just be fine. The concern is that logging may actually be important. E.g., for exchanges.

However... simply saying that we don't support this isn't unreasonable (as long as we document it).

> Edge case...

I'm pretty sure this was to make programming easier. No user would write `address.send(0)`, but a user _will_ write `address.send(some_variable)` where `some_variable` might be zero.

Without sending at least 2300 gas, this would fail and cause the contract to revert. This could cause problems if someone has written a generic "settle all accounts" function on some smart contract that doesn't handle accounts with no value.

On the other hand, I'm becoming more and more comfortable just documenting this as a known difference. Given that we're collecting a set of those anyways.

**Comment by wadeAlexC** [comment]
> That's what we currently do.

This is what I see on the latest commit on /next:

https://github.com/filecoin-project/builtin-actors/blob/43ebbffa12970d2f01dfce042d76707458945794/actors/evm/src/interpreter/instructions/call.rs#L240-L245

Not really the same, unless I'm missing something

**Comment by wadeAlexC** [comment]
Also, @vyzo mentioned yall were going with a "restricted call" concept, which I really want to avoid. I think it adds more complexity than its worth, and it's still not EVM compatible anyway so it will still have weird edge cases.

**Comment by wadeAlexC** [comment]
I did just think of another edge case, which is that `address.send(1 wei)` will fail for some contracts, simply because those contracts have explicitly chosen not to accept value sent like that. i.e. they don't have a `fallback/receive` function.

This would allow force-sending value to those contracts using `address.send` or `address.transfer`. It was always possible to force-send those contracts value by using selfdestruct, but this would add another way which may be triggered inadvertently.

I'm not sure it's a big deal, though.

**Comment by Stebalien** [comment]
> Not really the same, unless I'm missing something

Nope, I was missing something.

**Comment by Stebalien** [comment]
Fixed in https://github.com/filecoin-project/builtin-actors/pull/920
